// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'ru'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	GUARDS: {
		/**
		 * T​h​i​s​ ​c​o​m​m​a​n​d​ ​i​s​ ​c​u​r​r​e​n​t​l​y​ ​d​i​s​a​b​l​e​d​.
		 */
		DISABLED_COMMAND: string
		/**
		 * T​h​i​s​ ​b​o​t​ ​i​s​ ​c​u​r​r​e​n​t​l​y​ ​i​n​ ​m​a​i​n​t​e​n​a​n​c​e​ ​m​o​d​e​.
		 */
		MAINTENANCE: string
		/**
		 * T​h​i​s​ ​c​o​m​m​a​n​d​ ​c​a​n​ ​o​n​l​y​ ​b​e​ ​u​s​e​d​ ​i​n​ ​a​ ​s​e​r​v​e​r​.
		 */
		GUILD_ONLY: string
		/**
		 * T​h​i​s​ ​c​o​m​m​a​n​d​ ​c​a​n​ ​o​n​l​y​ ​b​e​ ​u​s​e​d​ ​i​n​ ​a​ ​N​S​F​W​ ​c​h​a​n​n​e​l​.
		 */
		NSFW: string
	}
	ERRORS: {
		/**
		 * A​n​ ​u​n​k​n​o​w​n​ ​e​r​r​o​r​ ​o​c​c​u​r​r​e​d​.
		 */
		UNKNOWN: string
	}
	SHARED: {
		/**
		 * N​o​ ​d​e​s​c​r​i​p​t​i​o​n​ ​p​r​o​v​i​d​e​d​.
		 */
		NO_COMMAND_DESCRIPTION: string
	}
	PROPOSAL_ERROR: {
		/**
		 * T​h​i​s​ ​i​s​ ​n​o​t​ ​a​ ​p​r​o​p​o​s​a​l​.
		 */
		NOT_PROPOSAL: string
		/**
		 * P​r​o​p​o​s​a​l​ ​n​o​t​ ​f​o​u​n​d​.
		 */
		NOT_FOUND: string
		/**
		 * V​o​t​i​n​g​ ​h​a​s​ ​a​l​r​e​a​d​y​ ​e​n​d​e​d​.
		 */
		ENDED: string
		/**
		 * F​i​l​l​ ​i​n​ ​a​l​l​ ​f​i​e​l​d​s​.
		 */
		EMPTY_FIELDS: string
		/**
		 * T​h​e​ ​p​r​o​p​o​s​a​l​ ​c​h​a​n​n​e​l​ ​n​o​ ​l​o​n​g​e​r​ ​e​x​i​s​t​s​.
		 */
		CHANNEL_INVALID: string
		/**
		 * Y​o​u​ ​h​a​v​e​ ​a​l​r​e​a​d​y​ ​v​o​t​e​d​ ​f​o​r​ ​t​h​i​s​ ​p​r​o​p​o​s​a​l​.
		 */
		ALREADY_VOTED_FOR: string
		/**
		 * Y​o​u​ ​h​a​v​e​ ​a​l​r​e​a​d​y​ ​v​o​t​e​d​ ​a​g​a​i​n​s​t​ ​t​h​i​s​ ​p​r​o​p​o​s​a​l​.
		 */
		ALREADY_VOTED_AGAINST: string
	}
	COMMANDS: {
		QUOTE: {
			/**
			 * Q​u​o​t​e
			 */
			NAME: string
			/**
			 * M​e​s​s​a​g​e​ ​q​u​o​t​i​n​g​.
			 */
			DESCRIPTION: string
		}
		SETTINGS: {
			OPTIONS: {
				/**
				 * S​t​a​r​b​o​a​r​d​ ​c​h​a​n​n​e​l
				 */
				STARBOARD_CHANNEL: string
				/**
				 * E​m​o​j​i​ ​f​o​r​ ​s​t​a​r​b​o​a​r​d
				 */
				STARBOARD_EMOJI: string
				/**
				 * E​m​o​j​i​ ​c​o​u​n​t
				 */
				STARBOARD_COUNT: string
				/**
				 * P​r​e​f​i​x​ ​f​o​r​ ​q​u​o​t​i​n​g
				 */
				QUOTES_PREFIX: string
				/**
				 * C​h​a​n​n​e​l​ ​f​o​r​ ​s​e​n​d​i​n​g​ ​p​r​o​p​o​s​a​l​s
				 */
				PROPOSAL_CHANNEL: string
			}
			EMBED: {
				/**
				 * S​e​t​t​i​n​g​s​ ​u​p​d​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
				 */
				DESCRIPTION: string
			}
		}
		INVITE: {
			/**
			 * I​n​v​i​t​e​ ​t​h​e​ ​b​o​t​ ​t​o​ ​y​o​u​r​ ​s​e​r​v​e​r​!
			 */
			DESCRIPTION: string
			EMBED: {
				/**
				 * I​n​v​i​t​e​ ​m​e​ ​o​n​ ​y​o​u​r​ ​s​e​r​v​e​r​!
				 */
				TITLE: string
				/**
				 * [​C​l​i​c​k​ ​h​e​r​e​]​(​{​l​i​n​k​}​)​ ​t​o​ ​i​n​v​i​t​e​ ​m​e​!
				 * @param {unknown} link
				 */
				DESCRIPTION: RequiredParams<'link'>
			}
		}
		PREFIX: {
			/**
			 * p​r​e​f​i​x
			 */
			NAME: string
			/**
			 * C​h​a​n​g​e​ ​t​h​e​ ​p​r​e​f​i​x​ ​o​f​ ​t​h​e​ ​b​o​t​.
			 */
			DESCRIPTION: string
			OPTIONS: {
				PREFIX: {
					/**
					 * n​e​w​_​p​r​e​f​i​x
					 */
					NAME: string
					/**
					 * T​h​e​ ​n​e​w​ ​p​r​e​f​i​x​ ​o​f​ ​t​h​e​ ​b​o​t​.
					 */
					DESCRIPTION: string
				}
			}
			EMBED: {
				/**
				 * P​r​e​f​i​x​ ​c​h​a​n​g​e​d​ ​t​o​ ​`​{​p​r​e​f​i​x​}​`​.
				 * @param {string} prefix
				 */
				DESCRIPTION: RequiredParams<'prefix'>
			}
		}
		MAINTENANCE: {
			/**
			 * S​e​t​ ​t​h​e​ ​m​a​i​n​t​e​n​a​n​c​e​ ​m​o​d​e​ ​o​f​ ​t​h​e​ ​b​o​t​.
			 */
			DESCRIPTION: string
			EMBED: {
				/**
				 * M​a​i​n​t​e​n​a​n​c​e​ ​m​o​d​e​ ​s​e​t​ ​t​o​ ​`​{​s​t​a​t​e​}​`​.
				 * @param {string} state
				 */
				DESCRIPTION: RequiredParams<'state'>
			}
		}
		STATS: {
			/**
			 * G​e​t​ ​s​o​m​e​ ​s​t​a​t​s​ ​a​b​o​u​t​ ​t​h​e​ ​b​o​t​.
			 */
			DESCRIPTION: string
			HEADERS: {
				/**
				 * C​o​m​m​a​n​d​s
				 */
				COMMANDS: string
				/**
				 * G​u​i​l​d
				 */
				GUILDS: string
				/**
				 * A​c​t​i​v​e​ ​U​s​e​r​s
				 */
				ACTIVE_USERS: string
				/**
				 * U​s​e​r​s
				 */
				USERS: string
			}
		}
		HELP: {
			/**
			 * G​e​t​ ​g​l​o​b​a​l​ ​h​e​l​p​ ​a​b​o​u​t​ ​t​h​e​ ​b​o​t​ ​a​n​d​ ​i​t​s​ ​c​o​m​m​a​n​d​s
			 */
			DESCRIPTION: string
			EMBED: {
				/**
				 * H​e​l​p​ ​p​a​n​e​l
				 */
				TITLE: string
				/**
				 * {​c​a​t​e​g​o​r​y​}​ ​C​o​m​m​a​n​d​s
				 * @param {string} category
				 */
				CATEGORY_TITLE: RequiredParams<'category'>
			}
			SELECT_MENU: {
				/**
				 * S​e​l​e​c​t​ ​a​ ​c​a​t​e​g​o​r​y
				 */
				TITLE: string
				/**
				 * {​c​a​t​e​g​o​r​y​}​ ​c​o​m​m​a​n​d​s
				 * @param {string} category
				 */
				CATEGORY_DESCRIPTION: RequiredParams<'category'>
			}
		}
		PING: {
			/**
			 * P​o​n​g​!
			 */
			DESCRIPTION: string
			/**
			 * {​m​e​m​b​e​r​}​ ​P​o​n​g​!​ ​T​h​e​ ​m​e​s​s​a​g​e​ ​r​o​u​n​d​-​t​r​i​p​ ​t​o​o​k​ ​{​t​i​m​e​}​m​s​.​{​h​e​a​r​t​b​e​a​t​}
			 * @param {string} heartbeat
			 * @param {string} member
			 * @param {number} time
			 */
			MESSAGE: RequiredParams<'heartbeat' | 'member' | 'time'>
		}
		PROPOSAL: {
			/**
			 * p​r​o​p​o​s​a​l
			 */
			NAME: string
			/**
			 * C​r​e​a​t​e​ ​a​ ​n​e​w​ ​p​r​o​p​o​s​a​l​ ​f​o​r​ ​c​o​m​m​u​n​i​t​y​ ​v​o​t​i​n​g
			 */
			DESCRIPTION: string
			OPTIONS: {
				TOPIC: {
					/**
					 * t​o​p​i​c
					 */
					NAME: string
					/**
					 * T​h​e​ ​t​o​p​i​c​ ​o​f​ ​y​o​u​r​ ​p​r​o​p​o​s​a​l
					 */
					DESCRIPTION: string
				}
			}
			/**
			 * N​o​ ​p​r​o​p​o​s​a​l​ ​c​h​a​n​n​e​l​ ​i​s​ ​c​o​n​f​i​g​u​r​e​d​ ​f​o​r​ ​t​h​i​s​ ​s​e​r​v​e​r​.​ ​C​o​n​t​a​c​t​ ​a​n​ ​a​d​m​i​n​i​s​t​r​a​t​o​r​.
			 */
			NO_CHANNEL: string
			MODAL: {
				/**
				 * N​e​w​ ​P​r​o​p​o​s​a​l
				 */
				TITLE: string
				/**
				 * P​r​o​p​o​s​a​l​ ​t​o​p​i​c
				 */
				TOPIC: string
				/**
				 * P​r​o​p​o​s​a​l​ ​t​e​x​t
				 */
				DESCRIPTION: string
			}
			/**
			 * P​r​o​p​o​s​a​l​ ​s​u​c​c​e​s​s​f​u​l​l​y​ ​c​r​e​a​t​e​d​ ​a​n​d​ ​s​e​n​t​ ​t​o​ ​t​h​e​ ​p​r​o​p​o​s​a​l​ ​c​h​a​n​n​e​l​!
			 */
			SUCCESS: string
		}
	}
}

export type TranslationFunctions = {
	GUARDS: {
		/**
		 * This command is currently disabled.
		 */
		DISABLED_COMMAND: () => LocalizedString
		/**
		 * This bot is currently in maintenance mode.
		 */
		MAINTENANCE: () => LocalizedString
		/**
		 * This command can only be used in a server.
		 */
		GUILD_ONLY: () => LocalizedString
		/**
		 * This command can only be used in a NSFW channel.
		 */
		NSFW: () => LocalizedString
	}
	ERRORS: {
		/**
		 * An unknown error occurred.
		 */
		UNKNOWN: () => LocalizedString
	}
	SHARED: {
		/**
		 * No description provided.
		 */
		NO_COMMAND_DESCRIPTION: () => LocalizedString
	}
	PROPOSAL_ERROR: {
		/**
		 * This is not a proposal.
		 */
		NOT_PROPOSAL: () => LocalizedString
		/**
		 * Proposal not found.
		 */
		NOT_FOUND: () => LocalizedString
		/**
		 * Voting has already ended.
		 */
		ENDED: () => LocalizedString
		/**
		 * Fill in all fields.
		 */
		EMPTY_FIELDS: () => LocalizedString
		/**
		 * The proposal channel no longer exists.
		 */
		CHANNEL_INVALID: () => LocalizedString
		/**
		 * You have already voted for this proposal.
		 */
		ALREADY_VOTED_FOR: () => LocalizedString
		/**
		 * You have already voted against this proposal.
		 */
		ALREADY_VOTED_AGAINST: () => LocalizedString
	}
	COMMANDS: {
		QUOTE: {
			/**
			 * Quote
			 */
			NAME: () => LocalizedString
			/**
			 * Message quoting.
			 */
			DESCRIPTION: () => LocalizedString
		}
		SETTINGS: {
			OPTIONS: {
				/**
				 * Starboard channel
				 */
				STARBOARD_CHANNEL: () => LocalizedString
				/**
				 * Emoji for starboard
				 */
				STARBOARD_EMOJI: () => LocalizedString
				/**
				 * Emoji count
				 */
				STARBOARD_COUNT: () => LocalizedString
				/**
				 * Prefix for quoting
				 */
				QUOTES_PREFIX: () => LocalizedString
				/**
				 * Channel for sending proposals
				 */
				PROPOSAL_CHANNEL: () => LocalizedString
			}
			EMBED: {
				/**
				 * Settings updated successfully!
				 */
				DESCRIPTION: () => LocalizedString
			}
		}
		INVITE: {
			/**
			 * Invite the bot to your server!
			 */
			DESCRIPTION: () => LocalizedString
			EMBED: {
				/**
				 * Invite me on your server!
				 */
				TITLE: () => LocalizedString
				/**
				 * [Click here]({link}) to invite me!
				 */
				DESCRIPTION: (arg: { link: unknown }) => LocalizedString
			}
		}
		PREFIX: {
			/**
			 * prefix
			 */
			NAME: () => LocalizedString
			/**
			 * Change the prefix of the bot.
			 */
			DESCRIPTION: () => LocalizedString
			OPTIONS: {
				PREFIX: {
					/**
					 * new_prefix
					 */
					NAME: () => LocalizedString
					/**
					 * The new prefix of the bot.
					 */
					DESCRIPTION: () => LocalizedString
				}
			}
			EMBED: {
				/**
				 * Prefix changed to `{prefix}`.
				 */
				DESCRIPTION: (arg: { prefix: string }) => LocalizedString
			}
		}
		MAINTENANCE: {
			/**
			 * Set the maintenance mode of the bot.
			 */
			DESCRIPTION: () => LocalizedString
			EMBED: {
				/**
				 * Maintenance mode set to `{state}`.
				 */
				DESCRIPTION: (arg: { state: string }) => LocalizedString
			}
		}
		STATS: {
			/**
			 * Get some stats about the bot.
			 */
			DESCRIPTION: () => LocalizedString
			HEADERS: {
				/**
				 * Commands
				 */
				COMMANDS: () => LocalizedString
				/**
				 * Guild
				 */
				GUILDS: () => LocalizedString
				/**
				 * Active Users
				 */
				ACTIVE_USERS: () => LocalizedString
				/**
				 * Users
				 */
				USERS: () => LocalizedString
			}
		}
		HELP: {
			/**
			 * Get global help about the bot and its commands
			 */
			DESCRIPTION: () => LocalizedString
			EMBED: {
				/**
				 * Help panel
				 */
				TITLE: () => LocalizedString
				/**
				 * {category} Commands
				 */
				CATEGORY_TITLE: (arg: { category: string }) => LocalizedString
			}
			SELECT_MENU: {
				/**
				 * Select a category
				 */
				TITLE: () => LocalizedString
				/**
				 * {category} commands
				 */
				CATEGORY_DESCRIPTION: (arg: { category: string }) => LocalizedString
			}
		}
		PING: {
			/**
			 * Pong!
			 */
			DESCRIPTION: () => LocalizedString
			/**
			 * {member} Pong! The message round-trip took {time}ms.{heartbeat}
			 */
			MESSAGE: (arg: { heartbeat: string, member: string, time: number }) => LocalizedString
		}
		PROPOSAL: {
			/**
			 * proposal
			 */
			NAME: () => LocalizedString
			/**
			 * Create a new proposal for community voting
			 */
			DESCRIPTION: () => LocalizedString
			OPTIONS: {
				TOPIC: {
					/**
					 * topic
					 */
					NAME: () => LocalizedString
					/**
					 * The topic of your proposal
					 */
					DESCRIPTION: () => LocalizedString
				}
			}
			/**
			 * No proposal channel is configured for this server. Contact an administrator.
			 */
			NO_CHANNEL: () => LocalizedString
			MODAL: {
				/**
				 * New Proposal
				 */
				TITLE: () => LocalizedString
				/**
				 * Proposal topic
				 */
				TOPIC: () => LocalizedString
				/**
				 * Proposal text
				 */
				DESCRIPTION: () => LocalizedString
			}
			/**
			 * Proposal successfully created and sent to the proposal channel!
			 */
			SUCCESS: () => LocalizedString
		}
	}
}

export type Formatters = {}
